/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.DefaultListModel;
import java.util.*;
/**
 *
 * @author Lenovo
 */
public class GuiLatihan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiLatihan.class.getName());
    private DefaultListModel<String> dlm;
    private List<String> listData = new ArrayList<>();
    private Set<String> setData = new HashSet<>();
    private Map<Integer, String> mapData = new HashMap<>();
    private int nextMapKey = 1;
    /**
     * Creates new form GuiLatihan
     */
    public GuiLatihan() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jITEMLIST.setModel(dlm);
        String[] contoh = {"buku", "meja", "kursi", "tas", "pintu jati", "tikus", "meja", "buku tulis", "tas"};
        for (String item : contoh) {
            dlm.addElement(item);
        }
        updateAllLabels();
    }
    private void addItem(String namaItem) {
        if (namaItem != null && !namaItem.trim().isEmpty()) {
            dlm.addElement(namaItem);
            jTextFieldNameItem.setText("");
        }
        updateAllLabels();
    }
    
    private void updateAllLabels() {
        jLabelList.setText("Data tersimpan = " + listData.size());
        jLabelSet.setText("Data tersimpan = " + setData.size());
        jLabelMap.setText("Data tersimpan = " + mapData.size());
    }
        private void updateAllCounters() {
        jLabelList.setText("Data tersimpan = " + listData.size());
        jLabelSet.setText("Data tersimpan = " + setData.size());
        jLabelMap.setText("Data tersimpan = " + mapData.size());
    }
    
    private void refreshListToCollection(Collection<String> target) {
        target.clear();
        for (int i = 0; i < dlm.getSize(); i++) {
            target.add(dlm.getElementAt(i));
        }
    }
    private void refreshListToSet() {
        setData.clear();
        for (int i = 0; i < dlm.getSize(); i++) {
            setData.add(dlm.getElementAt(i));
        }
    }
        private void refreshListToMap() {
        mapData.clear();
        nextMapKey = 1;
        for (int i = 0; i < dlm.getSize(); i++) {
            mapData.put(nextMapKey++, dlm.getElementAt(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jITEMLIST = new javax.swing.JList<>();
        jButtonSaveToList = new javax.swing.JButton();
        jButtonInsertDataList = new javax.swing.JButton();
        jButtonSaveToSet = new javax.swing.JButton();
        jButtonInsertDataSet = new javax.swing.JButton();
        jButtonSaveToMap = new javax.swing.JButton();
        jButtonInsertDataMap = new javax.swing.JButton();
        jLabelList = new javax.swing.JLabel();
        jLabelSet = new javax.swing.JLabel();
        jLabelMap = new javax.swing.JLabel();
        jTextFieldNameItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonClearAll = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jITEMLIST);

        jButtonSaveToList.setText("Save To List");
        jButtonSaveToList.addActionListener(this::jButtonSaveToListActionPerformed);

        jButtonInsertDataList.setText("Insert Data List");
        jButtonInsertDataList.addActionListener(this::jButtonInsertDataListActionPerformed);

        jButtonSaveToSet.setText("Save To Set");
        jButtonSaveToSet.addActionListener(this::jButtonSaveToSetActionPerformed);

        jButtonInsertDataSet.setText("Insert Data Set");
        jButtonInsertDataSet.addActionListener(this::jButtonInsertDataSetActionPerformed);

        jButtonSaveToMap.setText("Save To Map");
        jButtonSaveToMap.addActionListener(this::jButtonSaveToMapActionPerformed);

        jButtonInsertDataMap.setText("Insert Data Map");
        jButtonInsertDataMap.addActionListener(this::jButtonInsertDataMapActionPerformed);

        jLabelList.setText("Data Tersimpan =");

        jLabelSet.setText("Data Tersimpan =");

        jLabelMap.setText("Data Tersimpan =");

        jTextFieldNameItem.addActionListener(this::jTextFieldNameItemActionPerformed);

        jLabel4.setText("Item Nama");

        jButtonClearAll.setText("Clear all");
        jButtonClearAll.addActionListener(this::jButtonClearAllActionPerformed);

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(this::jButtonUpdateActionPerformed);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClearAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSaveToList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelList))
                            .addComponent(jButtonInsertDataList)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSaveToSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSet))
                            .addComponent(jButtonInsertDataSet)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSaveToMap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMap))
                            .addComponent(jButtonInsertDataMap)
                            .addComponent(jTextFieldNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveToList)
                            .addComponent(jLabelList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsertDataList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveToSet)
                            .addComponent(jLabelSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonInsertDataSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveToMap)
                            .addComponent(jLabelMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsertDataMap)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearAll)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToListActionPerformed
        refreshListToCollection(listData);
        updateAllCounters();
    }//GEN-LAST:event_jButtonSaveToListActionPerformed

    private void jTextFieldNameItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameItemActionPerformed
        addItem(jTextFieldNameItem.getText());

    }//GEN-LAST:event_jTextFieldNameItemActionPerformed

    private void jButtonInsertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataListActionPerformed
        refreshListToCollection(listData);
        updateAllCounters();
    }//GEN-LAST:event_jButtonInsertDataListActionPerformed

    private void jButtonSaveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToSetActionPerformed
        refreshListToSet();
        updateAllCounters();
    }//GEN-LAST:event_jButtonSaveToSetActionPerformed

    private void jButtonInsertDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataSetActionPerformed
        refreshListToSet();
        updateAllCounters();
    }//GEN-LAST:event_jButtonInsertDataSetActionPerformed

    private void jButtonSaveToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToMapActionPerformed
        refreshListToMap();
        updateAllCounters();
    }//GEN-LAST:event_jButtonSaveToMapActionPerformed

    private void jButtonInsertDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertDataMapActionPerformed
        refreshListToMap();
        updateAllCounters();
    }//GEN-LAST:event_jButtonInsertDataMapActionPerformed

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        dlm.clear();
        updateAllCounters();
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String newItem = jTextFieldNameItem.getText();
        if (newItem != null && !newItem.trim().isEmpty()) {
            dlm.addElement(newItem);
            jTextFieldNameItem.setText("");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        int idx = jITEMLIST.getSelectedIndex();
        if (idx != -1) {
            String newVal = jTextFieldNameItem.getText();
            if (newVal != null && !newVal.isEmpty()) {
                dlm.setElementAt(newVal, idx);
                jTextFieldNameItem.setText("");
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int idx = jITEMLIST.getSelectedIndex();
        if (idx != -1) {
            dlm.removeElementAt(idx);
            jTextFieldNameItem.setText("");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiLatihan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsertDataList;
    private javax.swing.JButton jButtonInsertDataMap;
    private javax.swing.JButton jButtonInsertDataSet;
    private javax.swing.JButton jButtonSaveToList;
    private javax.swing.JButton jButtonSaveToMap;
    private javax.swing.JButton jButtonSaveToSet;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JList<String> jITEMLIST;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelList;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelSet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNameItem;
    // End of variables declaration//GEN-END:variables
}
